database:
  name: taskboard_db
  user: postgres
  password: U1WzjeHW1uxUH9C0tZmL
  host: localhost
  port: 5432
admin:
  password: some-random-admin-password-123
jwt:
  secret_key: your_secret_key_here_change_in_production
  access_token_lifetime: 60
  refresh_token_lifetime: 1440
server:
  port: 8000
  debug: true
  allowed_hosts:
  - localhost
  - 127.0.0.1
